### ISSUE TITLE
Einfacher Aufruf im Frontend

### ISSUE THREAD

**Issue by olien** [factorylabs/redaxo_assets#2]
Hi,

ich würde mir einen einfachen Aufruf im Frontend wünschen wenn das möglich ist.

Bei SEO42 ging das z.B. so:

```php
    <link rel="stylesheet" href="<?php echo seo42::getCombinedCSSFile("combined.css", array(
"resources/screen.less",
"resources/test/bar.css",
"resources/responsive.scss"
)); ?>" type="text/css" media="screen,print" />

    <script type="text/javascript" src="<?php echo seo42::getCombinedJSFile("combined.js",
    array(
      "resources/jquery.cookiebar.js",
      "resources/equalheight_responsive.js",
      "domscript.js"
    )); ?>">
```

Das Ergebnis sind dann die Dateien combined.css und combined.js (die noch zu minifizieren wäre toll).

LG
Oliver

**Comment by Sioweb** [comment]
Ho!

Ja das ist hat Müll. Ich denke ich realisiere dass irgendwie im Backend. Da wählt man dann ein Set aus Dateien aus und kann das mit REX_ASSETS[type=css set=master] und dann kann man auch verschiedene Sets in unterschiedlichen Templates verwenden.

**Comment by olien** [comment]
Freu mich drauf. Coole Sache!

**Comment by Sioweb** [comment]
Ho!

In der neuen Version können im Backend Sets angelegt werden. Das Addon sucht dann die Pfade ab die in den Einstellungen definiert werden. Dann kann man dem Set einen Titel geben, eine Beschreibung und schlussendlich die Dateien zusammenklicken die man im Set haben möchte.

Im Template können diese Sets dann ausgegeben werden:

Title: Lorem

REX_ASSETS[type=css file=lorem]   
REX_ASSETS[type=js file=lorem]

Title: Ipsum

REX_ASSETS[type=css file=ipsum]   
REX_ASSETS[type=js file=ipsum]

### Vorteile

Im Frontend braucht es kein PHP-Code. Alle Dateien können theoretisch auch einmalig geparst werden und mit einem Link/Script-Tag ausgegeben werden.   
Verschiedene Templates können unterschiedliche Sets bekommen, wer ein Newsletter Template baut braucht ggf. ein anderes Set als eine Webseite.

Kannst du das mal testen, ob das so für dich nutzbar ist?

Danke!
lg Sascha

**Comment by olien** [comment]
Hi Sacha,

ich gucke mir das nächste Woche an. Da fange ich so langsam an mich auch mit dem Frontend zu beschäftigen.

Ich gebe dir 100% ein Feedback!!

LG
Oliver

**Comment by olien** [comment]
Super. Ich denke das kann ich schliessen :-)

DANKE
