### ISSUE TITLE
Installation: Fehler

### ISSUE THREAD

**Issue by olien** [factorylabs/redaxo_assets#5]
AddOn assets konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "SHOW COLUMNS FROM `rex_assets_sets`! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rex5beta2.rex_assets_sets' doesn't exist

REX - frisch von Github
Assets - frisch via Installer

**Comment by Sioweb** [comment]
Hm mist. Aber schau mal bitte nach, ich glaube das Addon wurde trotzdem Installiert?

**Comment by olien** [comment]
Nein

**Comment by Sioweb** [comment]
Ich hab nochmal ein Update hochgeladen, dass sollte funktionieren.

**Comment by olien** [comment]
Funktioniert! Danke!
